export const NEWS = {
    GET_NEWS: 'GET_NEWS',
    GET_NEWS_FAIELD: 'GET_NEWS_FAIELD',
    GET_NEWS_SUCCESS: 'GET_NEWS_SUCCESS',

    FAVORITE: 'FAVORITE',

    FAVORITE_LOCAL_STORAGE: 'FAVORITE_LOCAL_STORAGE',
    FAVORITE_LOCAL_STORAGE_INIT: 'FAVORITE_LOCAL_STORAGE_INIT',

    FAVORITE_ADD: 'FAVORITE_ADD',
    FAVORITE_REMOVE: 'FAVORITE_REMOVE',
    
    FAVORITE_ISSHOW: 'FAVORITE_ISSHOW',
    FAVORITE_TOGGLE: 'FAVORITE_TOGGLE'   
}

export const FILTER = {
    CHANGE_OPTION: 'CHANGE_OPTION',
    CHANGE_OPTIONS_ENDPOINT: 'CHANGE_OPTIONS_ENDPOINT',
    CHANGE_OPTIONS_CATEGORY: 'CHANGE_OPTIONS_CATEGORY',
    CHANGE_OPTIONS_SORTBY: 'CHANGE_OPTIONS_SORTBY',
    CHANGE_OPTIONS_SEARCH: 'CHANGE_OPTIONS_SEARCH',
    CHANGE_OPTIONS_CURRENTPAGE: 'CHANGE_OPTIONS_CURRENTPAGE',
    CHANGE_OPTIONS_PAGESIZE: 'CHANGE_OPTIONS_PAGESIZE',
    CHANGE_OPTIONS_ERROR: 'CHANGE_OPTIONS_ERROR'
}
